const coneSplitter = {
    0: {
      type: "Cone Splitter",
      name: "Example 1",
      price: 5000,
      compatible_attach: ["Excavator"],
      compatible_weight: ["Mini", "Medium"],
      compatible_flow: ["Standard", "High"],
      compatible_length: ["Short", "Medium", "Long"],
    },
    1: {
      type: "Cone Splitter",
      name: "Example 2",
      price: 8000,
      compatible_attach: ["Excavator"],
      compatible_weight: ["Medium", "Large"],
      compatible_flow: ["Standard", "High"],
      compatible_length: ["Short", "Medium"],
    },
    2: {
      type: "Cone Splitter",
      name: "Example 3",
      price: 10000,
      compatible_attach: ["Excavator", "Skid Steer"],
      compatible_weight: ["Mini", "Medium"],
      compatible_flow: ["Standard", "High"],
      compatible_length: ["Medium", "Long"],
    },
    3: {
      type: "Cone Splitter",
      name: "Example 4",
      price: 12000,
      compatible_attach: ["Skid Steer"],
      compatible_weight: ["Mini", "Large"],
      compatible_flow: ["Standard", "High"],
      compatible_length: ["Short", "Medium"],
    },
    4: {
      type: "Cone Splitter",
      name: "Example 5",
      price: 15000,
      compatible_attach: ["Skid Steer"],
      compatible_weight: ["Medium", "Large"],
      compatible_flow: ["Standard", "High"],
      compatible_length: ["Short", "Medium"],
    },
    5: {
      type: "Cone Splitter",
      name: "Example 6",
      price: 18000,
      compatible_attach: ["Excavator", "Skid Steer"],
      compatible_weight: ["Medium"],
      compatible_flow: ["Standard"],
      compatible_length: ["Short", "Medium"],
    },
    6: {
      type: "Cone Splitter",
      name: "Example 7",
      price: 22000,
      compatible_attach: ["Excavator"],
      compatible_weight: ["Mini", "Medium", "Large"],
      compatible_flow: ["Standard", "High"],
      compatible_length: ["Medium", "Long"],
    },
    7: {
      type: "Cone Splitter",
      name: "Example 8",
      price: 25000,
      compatible_attach: ["Skid Steer"],
      compatible_weight: ["Medium", "Large"],
      compatible_flow: ["Standard", "High"],
      compatible_length: ["Short", "Medium", "Long"],
    },
    8: {
      type: "Cone Splitter",
      name: "Example 9",
      price: 30000,
      compatible_attach: ["Excavator", "Skid Steer"],
      compatible_weight: ["Medium", "Large"],
      compatible_flow: ["Standard", "High"],
      compatible_length: ["Short", "Medium", "Long"],
    },
    9: {
      type: "Cone Splitter",
      name: "Example 10",
      price: 35000,
      compatible_attach: ["Excavator"],
      compatible_weight: ["Medium"],
      compatible_flow: ["High"],
      compatible_length: ["Short", "Medium"],
    },
    10: {
      type: "Cone Splitter",
      name: "Example 11",
      price: 40000,
      compatible_attach: ["Excavator", "Skid Steer"],
      compatible_weight: ["Mini", "Medium"],
      compatible_flow: ["Standard", "High"],
      compatible_length: ["Medium", "Long"],
    },
    11: {
      type: "Cone Splitter",
      name: "Example 12",
      price: 45000,
      compatible_attach: ["Excavator", "Skid Steer"],
      compatible_weight: ["Medium", "Large"],
      compatible_flow: ["High"],
      compatible_length: ["Medium", "Long"],
    },
  };
  
  export default coneSplitter;
  